"""
Prefix Tuning — Training with HuggingFace PEFT
=================================================

Complete training pipeline using PEFT's PrefixTuningConfig:

1. PrefixTuningConfig Deep Dive
   - All configuration options explained
   - Choosing the right settings

2. Training Pipeline
   - Model preparation
   - Dataset formatting
   - SFTTrainer integration

3. Saving, Loading, and Inference
   - Save/load prefix weights
   - Efficient inference patterns
   - Generation with prefix

4. Hyperparameter Tuning
   - Prefix length selection
   - Learning rate schedules
   - Training stability tips

Author: LLM Fine-Tuning Masterclass
"""

import torch
import torch.nn as nn
import os
import time
import math
from typing import Dict, Optional, Tuple
from dataclasses import dataclass


# ============================================================================
# SECTION 1: PrefixTuningConfig DEEP DIVE
# ============================================================================

def explain_prefix_config():
    """
    Detailed explanation of PEFT's PrefixTuningConfig parameters.
    """
    print("=" * 65)
    print("  SECTION 1: PrefixTuningConfig DEEP DIVE")
    print("=" * 65)
    
    explanation = """
  from peft import PrefixTuningConfig, TaskType
  
  config = PrefixTuningConfig(
      # ── Core Parameters ─────────────────────────────────────
      
      task_type=TaskType.CAUSAL_LM,
      # What type of task? Determines how the model head is used.
      # Options:
      #   TaskType.CAUSAL_LM          → Language modeling (GPT-style)
      #   TaskType.SEQ_2_SEQ_LM       → Encoder-decoder (T5-style)
      #   TaskType.SEQ_CLS            → Sequence classification
      #   TaskType.TOKEN_CLS          → Token classification (NER)
      #   TaskType.QUESTION_ANS       → Question answering
      
      num_virtual_tokens=20,
      # How many prefix tokens to prepend (the prefix_length).
      # This is THE most important hyperparameter.
      #
      # Guidelines:
      #   Simple tasks (sentiment): 5-10
      #   Medium tasks (NLI, QA):   10-30
      #   Complex tasks (generation): 20-50
      #   Very complex:             50-100
      #
      # Each virtual token adds d_model parameters × 2 (K+V) × n_layers
      # For GPT-2 (768d, 12 layers): 20 tokens = 20 × 768 × 2 × 12 = 368,640
      
      # ── Reparameterization ──────────────────────────────────
      
      encoder_hidden_size=768,
      # Dimension of the reparameterization MLP's hidden layer.
      # The prefix is generated by: Embedding → MLP → Prefix
      # Larger = more expressive reparameterization (but more params)
      # Default is usually model's hidden size.
      # Set to None to disable reparameterization (direct optimization).
      
      prefix_projection=True,
      # Whether to use the reparameterization MLP.
      # True (recommended):  Embedding(num_virtual_tokens, encoder_hidden_size)
      #                      → Linear → Tanh → Linear → prefix
      #                      More stable training
      # False:               Direct parameter optimization
      #                      Fewer params, but less stable
      
      # ── Inference ───────────────────────────────────────────
      
      inference_mode=False,
      # Set to True for inference (after training).
      # When True, the reparameterization MLP is discarded
      # and only the computed prefix values are kept.
      
      # ── Token Type ──────────────────────────────────────────
      
      token_dim=768,
      # Hidden size of the base model. Usually auto-detected.
      
      num_transformer_submodules=1,
      # Number of transformer submodules (e.g., 1 for decoder-only,
      # 2 for encoder-decoder). Usually auto-detected.
      
      num_attention_heads=12,
      # Number of attention heads. Usually auto-detected.
      
      num_layers=12,
      # Number of transformer layers. Usually auto-detected.
  )
"""
    print(explanation)
    
    # Show example configs for different scenarios
    print("\n  ── Example Configurations ──")
    
    configs = """
  # Minimal config (most common for GPT-2/LLaMA)
  simple_config = PrefixTuningConfig(
      task_type=TaskType.CAUSAL_LM,
      num_virtual_tokens=20,
  )
  
  # Config with reparameterization (recommended for stability)
  stable_config = PrefixTuningConfig(
      task_type=TaskType.CAUSAL_LM,
      num_virtual_tokens=30,
      prefix_projection=True,
      encoder_hidden_size=512,
  )
  
  # Lightweight config (fewer params)
  light_config = PrefixTuningConfig(
      task_type=TaskType.CAUSAL_LM,
      num_virtual_tokens=10,
      prefix_projection=False,  # No MLP
  )
  
  # For encoder-decoder models (T5, BART)
  enc_dec_config = PrefixTuningConfig(
      task_type=TaskType.SEQ_2_SEQ_LM,
      num_virtual_tokens=20,
      prefix_projection=True,
      encoder_hidden_size=512,
  )
"""
    print(configs)


# ============================================================================
# SECTION 2: TRAINING PIPELINE
# ============================================================================

@dataclass
class PrefixTrainingConfig:
    """Configuration for prefix tuning training."""
    # Model
    base_model_name: str = "distilgpt2"
    
    # Prefix
    num_virtual_tokens: int = 20
    prefix_projection: bool = True
    encoder_hidden_size: int = 512
    
    # Training
    output_dir: str = "./prefix_output"
    num_train_epochs: int = 3
    per_device_train_batch_size: int = 8
    gradient_accumulation_steps: int = 2
    learning_rate: float = 3e-2         # Prefix uses HIGH LR!
    weight_decay: float = 0.01
    warmup_ratio: float = 0.06
    lr_scheduler_type: str = "cosine"
    max_seq_length: int = 256
    
    # Logging
    logging_steps: int = 10
    save_strategy: str = "epoch"


def train_prefix_tuning(config: Optional[PrefixTrainingConfig] = None):
    """
    Complete prefix tuning training pipeline with PEFT.
    """
    if config is None:
        config = PrefixTrainingConfig()
    
    print("\n" + "=" * 65)
    print("  SECTION 2: PREFIX TUNING TRAINING PIPELINE")
    print("=" * 65)
    
    from transformers import (
        AutoModelForCausalLM,
        AutoTokenizer,
        TrainingArguments,
    )
    from peft import (
        PrefixTuningConfig,
        get_peft_model,
        TaskType,
    )
    from datasets import load_dataset
    from trl import SFTTrainer
    
    # ── Step 1: Load Base Model ──────────────────────────────────
    print(f"\n  [1/6] Loading {config.base_model_name}...")
    
    model = AutoModelForCausalLM.from_pretrained(config.base_model_name)
    tokenizer = AutoTokenizer.from_pretrained(config.base_model_name)
    
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        model.config.pad_token_id = tokenizer.pad_token_id
    
    base_params = sum(p.numel() for p in model.parameters())
    print(f"  Base model parameters: {base_params:,}")
    
    # ── Step 2: Configure Prefix Tuning ──────────────────────────
    print(f"\n  [2/6] Configuring prefix tuning "
          f"(tokens={config.num_virtual_tokens})...")
    
    peft_config = PrefixTuningConfig(
        task_type=TaskType.CAUSAL_LM,
        num_virtual_tokens=config.num_virtual_tokens,
        prefix_projection=config.prefix_projection,
        encoder_hidden_size=config.encoder_hidden_size,
    )
    
    # Apply prefix tuning to model
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()
    
    # Detailed parameter breakdown
    prefix_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"  Prefix parameters: {prefix_params:,}")
    print(f"  Trainable %: {prefix_params / base_params * 100:.4f}%")
    
    # ── Step 3: Prepare Dataset ──────────────────────────────────
    print(f"\n  [3/6] Preparing dataset...")
    
    dataset = load_dataset("Abirate/english_quotes", split="train")
    
    def format_example(example):
        quote = example.get("quote", "")
        author = example.get("author", "Unknown")
        return {"text": f"Quote: \"{quote}\" — {author}"}
    
    dataset = dataset.map(format_example, remove_columns=dataset.column_names)
    split = dataset.train_test_split(test_size=0.1, seed=42)
    
    print(f"  Train: {len(split['train'])} | Eval: {len(split['test'])}")
    
    # ── Step 4: Training Arguments ───────────────────────────────
    print(f"\n  [4/6] Setting up training...")
    
    training_args = TrainingArguments(
        output_dir=config.output_dir,
        num_train_epochs=config.num_train_epochs,
        per_device_train_batch_size=config.per_device_train_batch_size,
        gradient_accumulation_steps=config.gradient_accumulation_steps,
        learning_rate=config.learning_rate,
        weight_decay=config.weight_decay,
        warmup_ratio=config.warmup_ratio,
        lr_scheduler_type=config.lr_scheduler_type,
        logging_steps=config.logging_steps,
        save_strategy=config.save_strategy,
        save_total_limit=2,
        fp16=torch.cuda.is_available(),
        report_to="none",
        remove_unused_columns=False,
    )
    
    # ── Step 5: Train ────────────────────────────────────────────
    print(f"\n  [5/6] Training...")
    print(f"  LR: {config.learning_rate} (high for prefix tuning!)")
    
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=split["train"],
        eval_dataset=split["test"],
        processing_class=tokenizer,
    )
    
    start_time = time.time()
    result = trainer.train()
    train_time = time.time() - start_time
    
    print(f"  Training time: {train_time:.1f}s")
    print(f"  Final loss: {result.training_loss:.4f}")
    
    # ── Step 6: Save ─────────────────────────────────────────────
    print(f"\n  [6/6] Saving prefix to {config.output_dir}...")
    
    model.save_pretrained(config.output_dir)
    tokenizer.save_pretrained(config.output_dir)
    
    # Check saved size
    saved_size = sum(
        os.path.getsize(os.path.join(config.output_dir, f))
        for f in os.listdir(config.output_dir)
        if os.path.isfile(os.path.join(config.output_dir, f))
    ) / (1024 * 1024)
    
    print(f"  Saved size: {saved_size:.2f} MB")
    print(f"\n  ✓ Prefix tuning training complete!")
    
    return model, tokenizer, result


# ============================================================================
# SECTION 3: SAVING, LOADING, AND INFERENCE
# ============================================================================

def demonstrate_save_load_inference():
    """
    Saving, loading, and using prefix-tuned models.
    """
    print("\n" + "=" * 65)
    print("  SECTION 3: SAVING, LOADING, AND INFERENCE")
    print("=" * 65)
    
    code = '''
from peft import PeftModel, PeftConfig, PrefixTuningConfig
from transformers import AutoModelForCausalLM, AutoTokenizer

# ═══════════════════════════════════════════════════════════════
# SAVING PREFIX WEIGHTS
# ═══════════════════════════════════════════════════════════════

# After training:
model.save_pretrained("./prefix_output")
tokenizer.save_pretrained("./prefix_output")

# What gets saved:
# ./prefix_output/
# ├── adapter_config.json       # PrefixTuningConfig (JSON)
# ├── adapter_model.safetensors # Prefix parameters (~1-5 MB)
# └── tokenizer files...

# The saved files contain:
# 1. The prefix parameters (embedding + optional MLP)
# 2. The configuration (num_virtual_tokens, etc.)
# 3. NOT the base model weights (those are referenced by name)

# ═══════════════════════════════════════════════════════════════
# LOADING PREFIX WEIGHTS
# ═══════════════════════════════════════════════════════════════

# Load base model fresh
base_model = AutoModelForCausalLM.from_pretrained("distilgpt2")
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")

# Apply saved prefix weights
model = PeftModel.from_pretrained(
    base_model,
    "./prefix_output",
    is_trainable=False,  # Set to True for continued training
)

# The model now has the prefix applied automatically
# No further setup needed!

# ═══════════════════════════════════════════════════════════════
# INFERENCE / GENERATION
# ═══════════════════════════════════════════════════════════════

model.eval()

# Simple generation
inputs = tokenizer("Once upon a time", return_tensors="pt")
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
    )
text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(text)

# ═══════════════════════════════════════════════════════════════
# MULTIPLE PREFIX ADAPTERS
# ═══════════════════════════════════════════════════════════════

# Train prefix for task A, save
# Train prefix for task B, save

base_model = AutoModelForCausalLM.from_pretrained("distilgpt2")

# Load task A prefix
model = PeftModel.from_pretrained(base_model, "./prefix_task_a")

# Add task B prefix
model.load_adapter("./prefix_task_b", adapter_name="task_b")

# Switch between tasks
model.set_adapter("default")    # Use task A prefix
model.set_adapter("task_b")     # Use task B prefix
'''
    print(code)
    
    # Run actual demo
    print("\n  ── Running Live Demo ──")
    
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PrefixTuningConfig, get_peft_model, TaskType
    
    model = AutoModelForCausalLM.from_pretrained("distilgpt2")
    tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
    tokenizer.pad_token = tokenizer.eos_token
    
    # Create and apply prefix config
    peft_config = PrefixTuningConfig(
        task_type=TaskType.CAUSAL_LM,
        num_virtual_tokens=20,
        prefix_projection=True,
        encoder_hidden_size=256,
    )
    
    model = get_peft_model(model, peft_config)
    model.eval()
    
    # Generate with prefix (untrained — just shows it works)
    prompt = "The quick brown fox"
    inputs = tokenizer(prompt, return_tensors="pt")
    
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=30,
            do_sample=True,
            temperature=0.8,
            top_p=0.9,
        )
    
    generated = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(f"\n  Prompt:    \"{prompt}\"")
    print(f"  Generated: \"{generated}\"")
    print(f"  (Untrained prefix — output is random but shows pipeline works)")
    
    # Show model structure
    print(f"\n  ── Model Structure ──")
    prefix_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"  Trainable (prefix): {prefix_params:,}")
    print(f"  Total:              {total_params:,}")
    print(f"  Prefix %:           {prefix_params/total_params*100:.4f}%")


# ============================================================================
# SECTION 4: HYPERPARAMETER TUNING
# ============================================================================

class PrefixHyperparameterGuide:
    """
    Comprehensive hyperparameter guide for prefix tuning.
    """
    
    @staticmethod
    def learning_rate_analysis():
        """Analyze learning rate impact on prefix tuning."""
        print("\n" + "=" * 65)
        print("  SECTION 4: HYPERPARAMETER TUNING")
        print("=" * 65)
        
        guide = """
  ═══════════════════════════════════════════════════════════════
   LEARNING RATE — THE MOST CRITICAL HYPERPARAMETER
  ═══════════════════════════════════════════════════════════════
  
  Prefix tuning requires MUCH HIGHER learning rates than other methods!
  
  Why? The prefix parameters are:
  1. Randomly initialized (no pre-trained values to start from)
  2. Only a small number of parameters (needs large updates)
  3. Indirectly influencing the model (through attention)
  
  ┌──────────────────────────────────────────────────────────────┐
  │  Method           │  Typical LR    │  Why?                   │
  ├──────────────────────────────────────────────────────────────┤
  │  Full Fine-Tuning │  1e-5 to 5e-5  │  Many params, pretrained│
  │  LoRA             │  1e-4 to 3e-4  │  Moderate # params      │
  │  Adapters         │  1e-3 to 5e-3  │  New params, random init│
  │  Prefix Tuning    │  1e-2 to 5e-2  │  Few params, indirect ★ │
  │  Prompt Tuning    │  3e-1 to 1e0   │  Very few params!       │
  └──────────────────────────────────────────────────────────────┘
  
  ★ Prefix tuning LR is 100-1000× higher than full fine-tuning!
  
  Recommended LR ranges by prefix configuration:
  ─────────────────────────────────────────────────────────────
  With reparameterization:     1e-2 to 5e-2
  Without reparameterization:  1e-3 to 1e-2  (lower, more unstable)
  
  If training diverges: reduce LR and increase warmup
  If training is slow:  increase LR by 2-5×
"""
        print(guide)
    
    @staticmethod
    def prefix_length_guide():
        """Guide for choosing prefix length."""
        print("\n  ═══ PREFIX LENGTH SELECTION ═══")
        
        guide = """
  num_virtual_tokens: How many prefix vectors to prepend at each layer
  
  ┌──────────────────────────────────────────────────────────────┐
  │  Prefix Length │ Parameters† │ Use Case                      │
  ├──────────────────────────────────────────────────────────────┤
  │  5             │    ~92K     │ Very simple tasks, large data │
  │  10            │   ~184K     │ Simple classification         │
  │  20            │   ~369K     │ ★ Best default starting point │
  │  30            │   ~553K     │ Complex NLU tasks             │
  │  50            │   ~922K     │ Generation tasks              │
  │  100           │  ~1,843K    │ Very complex, enough data     │
  │  200           │  ~3,686K    │ Rarely needed, context waste  │
  └──────────────────────────────────────────────────────────────┘
  † For GPT-2 (768d, 12 layers), with reparameterization
  
  Decision tree:
  ─────────────────────────────────────────────────────────────
  1. Start with num_virtual_tokens = 20
  2. If underfitting (train loss high): increase to 30-50
  3. If overfitting (val loss diverges): decrease to 10
  4. If context window matters: keep prefix < 5% of context
  5. Tune by trying {5, 10, 20, 50} on validation set
"""
        print(guide)
    
    @staticmethod
    def training_stability_tips():
        """Tips for stable prefix tuning training."""
        print("\n  ═══ TRAINING STABILITY TIPS ═══")
        
        tips = """
  1. ALWAYS USE REPARAMETERIZATION
     prefix_projection=True
     Without it, optimization landscape is difficult.
     The MLP smooths the loss surface considerably.
     
  2. WARM UP THE LEARNING RATE
     warmup_ratio=0.06 to 0.10
     Prefix parameters are randomly initialized — they need
     gentle initial training to find a good region.
     
  3. USE COSINE LR SCHEDULE
     lr_scheduler_type="cosine"
     Better than linear decay for prefix tuning.
     The gradual decay helps fine-tune the prefix in later steps.
     
  4. GRADIENT CLIPPING
     max_grad_norm=1.0
     Essential for preventing sudden loss spikes.
     Prefix gradients can be large due to the softmax dependency.
     
  5. BATCH SIZE MATTERS
     Use effective batch size ≥ 16
     Prefix tuning benefits from stable gradient estimates.
     Use gradient accumulation if GPU memory is limited.
     
  6. AVOID VERY LONG SEQUENCES INITIALLY
     Start with max_seq_length = 256
     Longer sequences → more attention positions → noisier
     prefix gradients. Increase after initial convergence.
     
  7. MONITOR PREFIX NORMS
     If prefix parameter norms explode → reduce LR
     If they collapse to zero → increase LR
     
  8. TRAINING EPOCHS
     3-10 epochs typically sufficient.
     Prefix tuning converges faster than full FT.
     Watch for overfitting after epoch 5.
"""
        print(tips)
    
    @staticmethod
    def run_lr_sweep_demo():
        """Demonstrate a learning rate sweep (simulated)."""
        print("\n  ═══ LEARNING RATE SWEEP (SIMULATED) ═══")
        
        # Simulated results for different LRs
        lr_results = [
            (1e-5, "Did not converge — LR too low for prefix tuning",
             5.2, 5.1, "✗"),
            (1e-4, "Very slow convergence, needs many more epochs",
             4.8, 4.6, "~"),
            (1e-3, "Converging but slow",
             3.5, 3.2, "~"),
            (1e-2, "Good convergence, smooth loss curve",
             2.1, 2.3, "★"),
            (3e-2, "Best results — fast convergence, good final loss",
             1.8, 2.0, "★★"),
            (5e-2, "Good convergence, slightly less stable",
             1.9, 2.1, "★"),
            (1e-1, "Training unstable, loss spikes",
             2.5, 3.8, "~"),
            (5e-1, "Diverged after epoch 1",
             float('inf'), float('inf'), "✗"),
        ]
        
        print(f"\n  {'LR':>8} {'Train Loss':>12} {'Val Loss':>10} "
              f"{'Rating':>8} {'Notes':>40}")
        print(f"  {'─'*8}─{'─'*12}─{'─'*10}─{'─'*8}─{'─'*40}")
        
        for lr, notes, train_loss, val_loss, rating in lr_results:
            tl = f"{train_loss:.2f}" if train_loss < 100 else "NaN"
            vl = f"{val_loss:.2f}" if val_loss < 100 else "NaN"
            print(f"  {lr:>8.0e}  {tl:>10}  {vl:>8}    {rating:>4}   {notes}")
        
        print(f"\n  → Best LR for prefix tuning: 1e-2 to 5e-2")
        print(f"    (with reparameterization and warmup)")


# ============================================================================
# SECTION 5: COMPLETE TRAINING EXAMPLE
# ============================================================================

def complete_prefix_training_example():
    """
    Put it all together: a complete, production-ready prefix tuning pipeline.
    """
    print("\n" + "=" * 65)
    print("  COMPLETE PREFIX TUNING EXAMPLE")
    print("=" * 65)
    
    code = '''
import torch
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, TrainingArguments
)
from peft import PrefixTuningConfig, get_peft_model, TaskType, PeftModel
from datasets import load_dataset
from trl import SFTTrainer

# ══ Configuration ══════════════════════════════════════════════
BASE_MODEL = "distilgpt2"        # Or "meta-llama/Llama-2-7b-hf" etc.
NUM_VIRTUAL_TOKENS = 20          # Start here, tune if needed
LEARNING_RATE = 3e-2             # High LR for prefix tuning!
EPOCHS = 3
BATCH_SIZE = 8
OUTPUT_DIR = "./prefix_sentiment"

# ══ Load Model & Tokenizer ════════════════════════════════════
model = AutoModelForCausalLM.from_pretrained(BASE_MODEL)
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.pad_token_id

# ══ Apply Prefix Tuning ═══════════════════════════════════════
peft_config = PrefixTuningConfig(
    task_type=TaskType.CAUSAL_LM,
    num_virtual_tokens=NUM_VIRTUAL_TOKENS,
    prefix_projection=True,              # Use reparameterization MLP
    encoder_hidden_size=512,             # MLP hidden dimension
)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

# ══ Prepare Data ══════════════════════════════════════════════
dataset = load_dataset("imdb", split="train[:5000]")
def format_fn(example):
    label = "positive" if example["label"] == 1 else "negative"
    text = example["text"][:500]  # Truncate long reviews
    return {"text": f"Review: {text}\\nSentiment: {label}"}

dataset = dataset.map(format_fn, remove_columns=dataset.column_names)
split = dataset.train_test_split(test_size=0.1, seed=42)

# ══ Training ═══════════════════════════════════════════════════
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=2,        # Effective batch = 16
    learning_rate=LEARNING_RATE,
    lr_scheduler_type="cosine",
    warmup_ratio=0.06,
    weight_decay=0.01,
    max_grad_norm=1.0,                    # Gradient clipping
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=2,
    fp16=torch.cuda.is_available(),
    report_to="none",
    remove_unused_columns=False,
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=split["train"],
    eval_dataset=split["test"],
    processing_class=tokenizer,
)

trainer.train()

# ══ Save ══════════════════════════════════════════════════════
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# ══ Load and Use ══════════════════════════════════════════════
# Fresh load for inference
base_model = AutoModelForCausalLM.from_pretrained(BASE_MODEL)
model = PeftModel.from_pretrained(base_model, OUTPUT_DIR)
model.eval()

prompt = "Review: This movie was absolutely fantastic!\\nSentiment:"
inputs = tokenizer(prompt, return_tensors="pt")

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=10,
        do_sample=False,  # Greedy for classification
    )

result = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(result)
# Expected: "Review: This movie was...\\nSentiment: positive"
'''
    print(code)


# ============================================================================
# MAIN
# ============================================================================

def main():
    """Run all prefix training demonstrations."""
    print("╔════════════════════════════════════════════════════════════════╗")
    print("║         PREFIX TUNING — TRAINING WITH PEFT                   ║")
    print("╚════════════════════════════════════════════════════════════════╝")
    
    # Section 1: Config deep dive
    explain_prefix_config()
    
    # Section 2: Training pipeline
    config = PrefixTrainingConfig(
        num_train_epochs=1,
        per_device_train_batch_size=4,
        num_virtual_tokens=10,
        save_strategy="no",
        logging_steps=5,
    )
    train_prefix_tuning(config)
    
    # Section 3: Save/load/inference
    demonstrate_save_load_inference()
    
    # Section 4: Hyperparameters
    hp = PrefixHyperparameterGuide()
    hp.learning_rate_analysis()
    hp.prefix_length_guide()
    hp.training_stability_tips()
    hp.run_lr_sweep_demo()
    
    # Section 5: Complete example
    complete_prefix_training_example()
    
    print("\n" + "=" * 65)
    print("  MODULE COMPLETE")
    print("=" * 65)
    print("""
    Covered:
    ✓ PrefixTuningConfig — all parameters explained
    ✓ Complete training pipeline with PEFT + SFTTrainer
    ✓ Saving, loading, and inference patterns
    ✓ Hyperparameter guide (LR, prefix length, stability)
    ✓ Learning rate sweep analysis
    ✓ Production-ready training example
    """)


if __name__ == "__main__":
    main()
